-- Catálogo inicial: 17 tópicos e 82 animações; execute após a migração principal.
-- Os arquivos .blend existentes continuam públicos na raiz do site.
begin;
insert into public.animations(title,topic,slug,summary,level,is_published)
values
  ('Movimento retilíneo uniforme (MRU)','Cinemática','cinematica--mru','Um carrinho percorre distâncias iguais em intervalos de tempo iguais. Compare a posição em cada quadro e acompanhe o gráfico posição × tempo.','Ensino médio',true),
  ('Movimento retilíneo uniformemente variado (MRUV)','Cinemática','cinematica--mruv','Veja a velocidade mudar de maneira regular e observe como a distância percorrida cresce a cada intervalo.','Ensino médio',true),
  ('Aceleração e frenagem','Cinemática','cinematica--aceleracao-frenagem','Compare o sentido da velocidade e da aceleração enquanto um veículo ganha velocidade e depois freia.','Ensino médio',true),
  ('Queda livre','Cinemática','cinematica--queda-livre','Acompanhe objetos em queda e compare suas posições em intervalos iguais, desconsiderando a resistência do ar.','Ensino médio',true),
  ('Lançamento oblíquo','Cinemática','cinematica--lancamento-obliquo','Observe a trajetória de um projétil como a combinação de movimentos horizontal e vertical.','Ensino médio',true),
  ('Movimento circular','Cinemática','cinematica--movimento-circular','Siga um corpo em uma circunferência e compare sua velocidade com a aceleração dirigida para o centro.','Ensino médio',true),
  ('Primeira lei: inércia','Dinâmica','dinamica--lei-inercia','Compare o movimento de um objeto quando a força resultante é nula e quando uma força externa passa a atuar.','Ensino médio',true),
  ('Segunda lei: força e aceleração','Dinâmica','dinamica--forca-aceleracao','Mude a força aplicada ou a massa e observe como a aceleração responde.','Ensino médio',true),
  ('Terceira lei: ação e reação','Dinâmica','dinamica--acao-reacao','Veja as forças que dois corpos exercem um sobre o outro durante um empurrão e uma colisão.','Ensino médio',true),
  ('Atrito em uma rampa','Dinâmica','dinamica--atrito-rampa','Observe as forças paralela e perpendicular ao plano e o papel do atrito no movimento.','Ensino médio',true),
  ('Tração em sistemas de polias','Dinâmica','dinamica--tracao-polia','Acompanhe a tensão nos fios e o movimento de duas massas conectadas.','Ensino médio',true),
  ('Força centrípeta','Dinâmica','dinamica--forca-centripeta','Identifique a força resultante que mantém um objeto em trajetória circular.','Ensino médio',true),
  ('Equilíbrio de forças','Estática','estatica--equilibrio-forcas','Monte um diagrama vetorial e observe forças opostas se cancelarem.','Ensino médio',true),
  ('Alavancas e torque','Estática','estatica--alavancas-torque','Mude a posição de uma carga e compare o efeito de aplicar força perto ou longe do apoio.','Ensino médio',true),
  ('Centro de massa e estabilidade','Estática','estatica--centro-massa','Desloque o centro de massa e compare quando uma estrutura se mantém estável ou tomba.','Ensino médio',true),
  ('Atração gravitacional','Gravitação','gravitacao--atracao-gravitacional','Compare como a força gravitacional muda com a massa e a distância entre dois corpos.','Ensino médio',true),
  ('Órbita de um satélite','Gravitação','gravitacao--orbita-satelite','Altere a velocidade tangencial e observe trajetórias orbitais diferentes em torno de um planeta.','Ensino médio',true),
  ('Leis de Kepler','Gravitação','gravitacao--leis-kepler','Acompanhe uma órbita elíptica e a variação da velocidade do planeta ao longo do percurso.','Ensino médio',true),
  ('Peso em diferentes astros','Gravitação','gravitacao--peso-astros','Compare a força peso sobre a mesma massa em campos gravitacionais distintos.','Ensino médio',true),
  ('Trabalho de uma força','Trabalho, energia e potência','trabalho-energia--trabalho-forca','Compare uma força que acompanha o deslocamento com uma força perpendicular a ele.','Ensino médio',true),
  ('Energia cinética e velocidade','Trabalho, energia e potência','trabalho-energia--energia-cinetica','Aumente a velocidade de um objeto e acompanhe o crescimento de sua energia cinética.','Ensino médio',true),
  ('Energia potencial gravitacional','Trabalho, energia e potência','trabalho-energia--energia-potencial','Observe energia potencial e cinética se transformarem durante uma descida.','Ensino médio',true),
  ('Conservação da energia mecânica','Trabalho, energia e potência','trabalho-energia--conservacao-energia','Acompanhe uma esfera em uma pista e veja energia potencial e cinética variarem.','Ensino médio',true),
  ('Potência em uma subida','Trabalho, energia e potência','trabalho-energia--potencia','Compare o tempo de duas subidas iguais e relacione trabalho realizado e potência.','Ensino médio',true),
  ('Quantidade de movimento','Quantidade de movimento e impulso','quantidade-movimento--quantidade-movimento','Compare corpos de massas e velocidades diferentes antes de uma colisão.','Ensino médio',true),
  ('Impulso de uma força','Quantidade de movimento e impulso','quantidade-movimento--impulso','Varie a duração de uma força e observe a mudança da quantidade de movimento.','Ensino médio',true),
  ('Colisão elástica','Quantidade de movimento e impulso','quantidade-movimento--colisao-elastica','Acompanhe dois carrinhos antes e depois de uma colisão ideal com conservação de energia cinética.','Ensino médio',true),
  ('Colisão inelástica','Quantidade de movimento e impulso','quantidade-movimento--colisao-inelastica','Observe objetos que permanecem unidos após a colisão e compare o movimento do conjunto.','Ensino médio',true),
  ('Segurança e tempo de colisão','Quantidade de movimento e impulso','quantidade-movimento--tempo-colisao','Compare como aumentar o tempo de impacto pode reduzir a força média em uma colisão.','Ensino médio',true),
  ('Pressão com a profundidade','Hidrostática','hidrostatica--pressao-profundidade','Compare a pressão em pontos diferentes de uma coluna de líquido.','Ensino médio',true),
  ('Princípio de Pascal','Hidrostática','hidrostatica--principio-pascal','Acompanhe como uma pressão aplicada a um fluido confinado se transmite pelo sistema hidráulico.','Ensino médio',true),
  ('Empuxo e flutuação','Hidrostática','hidrostatica--empuxo-flutuacao','Mude o volume submerso de um objeto e observe as forças de peso e empuxo.','Ensino médio',true),
  ('Vasos comunicantes','Hidrostática','hidrostatica--vasos-comunicantes','Observe o equilíbrio do líquido em recipientes conectados de formatos diferentes.','Ensino médio',true),
  ('Temperatura e partículas','Termologia','termologia--temperatura-particulas','Compare a agitação média das partículas em materiais a temperaturas diferentes.','Ensino médio',true),
  ('Condução, convecção e radiação','Termologia','termologia--transferencia-calor','Veja três maneiras de transferir energia térmica em situações cotidianas.','Ensino médio',true),
  ('Dilatação térmica','Termologia','termologia--dilatacao-termica','Acompanhe a expansão de uma barra ao ser aquecida e a contração ao esfriar.','Ensino médio',true),
  ('Mudanças de estado','Termologia','termologia--mudancas-estado','Visualize partículas durante fusão, vaporização e condensação.','Ensino médio',true),
  ('Calorimetria','Termologia','termologia--calorimetria','Misture porções de água a temperaturas diferentes e observe a troca de energia térmica.','Ensino médio',true),
  ('Primeira lei da Termodinâmica','Termodinâmica','termodinamica--primeira-lei','Siga a energia que entra como calor, o trabalho realizado e a mudança da energia interna.','Ensino médio',true),
  ('Transformações de um gás','Termodinâmica','termodinamica--transformacoes-gasosas','Compare processos isobárico, isotérmico, isovolumétrico e adiabático em diagramas.','Ensino médio',true),
  ('Diagrama pressão × volume','Termodinâmica','termodinamica--diagrama-pv','Observe o trabalho associado à expansão ou compressão de um gás.','Ensino médio',true),
  ('Máquina térmica','Termodinâmica','termodinamica--maquina-termica','Acompanhe calor recebido, trabalho útil e calor rejeitado em um ciclo idealizado.','Ensino médio',true),
  ('Refrigerador','Termodinâmica','termodinamica--refrigerador','Veja como trabalho externo permite transferir energia térmica da região fria para a quente.','Ensino médio',true),
  ('Pulso em uma corda','Ondulatória','ondulatoria--pulso-corda','Siga a propagação de um pulso e perceba que a perturbação avança enquanto a corda oscila localmente.','Ensino médio',true),
  ('Ondas transversais e longitudinais','Ondulatória','ondulatoria--tipos-onda','Compare a direção de vibração das partículas com a direção em que cada onda se propaga.','Ensino médio',true),
  ('Frequência e comprimento de onda','Ondulatória','ondulatoria--frequencia-comprimento','Altere a frequência e observe o espaçamento entre cristas em um mesmo meio.','Ensino médio',true),
  ('Reflexão e refração de ondas','Ondulatória','ondulatoria--reflexao-refracao','Observe uma onda refletida e uma onda que muda de direção ao entrar em outro meio.','Ensino médio',true),
  ('Interferência e ondas estacionárias','Ondulatória','ondulatoria--interferencia','Sobreponha ondas e observe regiões de reforço e cancelamento.','Ensino médio',true),
  ('Como o som se propaga','Acústica','acustica--propagacao-som','Visualize compressões e rarefações avançando pelo ar a partir de uma fonte vibrante.','Ensino médio',true),
  ('Altura e intensidade sonora','Acústica','acustica--altura-intensidade','Compare frequência e amplitude para distinguir sons graves/agudos e fracos/fortes.','Ensino médio',true),
  ('Ressonância em uma coluna de ar','Acústica','acustica--ressonancia','Observe como certas frequências formam padrões de ressonância em um tubo.','Ensino médio',true),
  ('Efeito Doppler','Acústica','acustica--efeito-doppler','Compare a frequência percebida enquanto uma fonte sonora se aproxima e se afasta.','Ensino médio',true),
  ('Eco e reflexão sonora','Acústica','acustica--eco-reflexao','Acompanhe o caminho do som até uma superfície refletora e de volta ao ouvinte.','Ensino médio',true),
  ('Reflexão em espelhos','Óptica','optica--reflexao-espelhos','Trace raios incidentes e refletidos e compare seus ângulos.','Ensino médio',true),
  ('Refração da luz','Óptica','optica--refracao-luz','Observe a mudança de direção da luz ao passar entre meios diferentes.','Ensino médio',true),
  ('Lentes convergentes e divergentes','Óptica','optica--lentes','Acompanhe raios principais e compare como cada lente forma imagens.','Ensino médio',true),
  ('Formação de arco-íris','Óptica','optica--dispersao-luz','Visualize a dispersão da luz branca em diferentes cores ao atravessar uma gota.','Ensino médio',true),
  ('Câmara escura','Óptica','optica--camara-escura','Veja como raios de luz formam uma imagem invertida através de um pequeno orifício.','Ensino médio',true),
  ('Eletrização por atrito e contato','Eletrostática','eletrostatica--eletrizacao','Acompanhe a transferência e a redistribuição de elétrons entre objetos.','Ensino médio',true),
  ('Lei de Coulomb','Eletrostática','eletrostatica--lei-coulomb','Compare a força entre duas cargas ao variar seus valores e a distância.','Ensino médio',true),
  ('Campo elétrico','Eletrostática','eletrostatica--campo-eletrico','Explore linhas de campo em torno de cargas positivas, negativas e pares de cargas.','Ensino médio',true),
  ('Potencial elétrico','Eletrostática','eletrostatica--potencial-eletrico','Observe superfícies equipotenciais ao redor de diferentes distribuições de carga.','Ensino médio',true),
  ('Capacitor de placas paralelas','Eletrostática','eletrostatica--capacitor','Varie carga e distância entre placas e observe o campo entre elas.','Ensino médio',true),
  ('Corrente em um circuito simples','Eletrodinâmica','eletrodinamica--corrente-circuito','Siga a corrente convencional em um circuito com fonte, fios e lâmpada.','Ensino médio',true),
  ('Lei de Ohm','Eletrodinâmica','eletrodinamica--lei-ohm','Mude a tensão ou a resistência e compare a corrente no circuito.','Ensino médio',true),
  ('Resistores em série e paralelo','Eletrodinâmica','eletrodinamica--resistores-serie-paralelo','Compare a corrente e a tensão em duas formas de associar resistores.','Ensino médio',true),
  ('Potência e efeito Joule','Eletrodinâmica','eletrodinamica--efeito-joule','Observe a transformação de energia elétrica em energia térmica em um resistor.','Ensino médio',true),
  ('Instrumentos de medida','Eletrodinâmica','eletrodinamica--medidas-circuito','Veja onde conectar amperímetro e voltímetro para medir corrente e tensão.','Ensino médio',true),
  ('Campo de um ímã','Magnetismo','magnetismo--campo-ima','Explore a orientação das linhas de campo em torno de um ímã de barra.','Ensino médio',true),
  ('Força magnética sobre uma carga','Magnetismo','magnetismo--forca-carga','Varie velocidade e orientação para comparar a força magnética sobre uma carga em movimento.','Ensino médio',true),
  ('Força em um fio com corrente','Magnetismo','magnetismo--forca-fio','Observe a força sobre um condutor percorrido por corrente dentro de um campo magnético.','Ensino médio',true),
  ('Bússola e campo terrestre','Magnetismo','magnetismo--campo-terrestre','Acompanhe a orientação de uma bússola em diferentes posições ao redor da Terra.','Ensino médio',true),
  ('Ímã e bobina','Indução eletromagnética','eletromagnetismo--ima-bobina','Mova um ímã em relação a uma bobina e observe quando surge corrente induzida.','Ensino médio',true),
  ('Lei de Lenz','Indução eletromagnética','eletromagnetismo--lei-lenz','Compare o sentido da corrente induzida com a mudança que a produziu.','Ensino médio',true),
  ('Gerador elétrico','Indução eletromagnética','eletromagnetismo--gerador-eletrico','Acompanhe a rotação de uma espira e a produção de tensão alternada.','Ensino médio',true),
  ('Motor elétrico','Indução eletromagnética','eletromagnetismo--motor-eletrico','Observe como a interação entre corrente e campo magnético produz rotação.','Ensino médio',true),
  ('Transformador','Indução eletromagnética','eletromagnetismo--transformador','Compare o número de espiras e a tensão nos enrolamentos de um transformador.','Ensino médio',true),
  ('Modelos do átomo','Física moderna e nuclear','fisica-moderna--modelos-atomo','Compare representações históricas do átomo e veja como cada modelo responde a perguntas diferentes.','Ensino médio',true),
  ('Efeito fotoelétrico','Física moderna e nuclear','fisica-moderna--efeito-fotoeletrico','Varie frequência e intensidade da luz para distinguir energia dos fótons e quantidade de elétrons emitidos.','Ensino médio',true),
  ('Decaimento radioativo','Física moderna e nuclear','fisica-moderna--decaimento-radioativo','Visualize decaimento como processo probabilístico e acompanhe a meia-vida de uma amostra.','Ensino médio',true),
  ('Fissão nuclear','Física moderna e nuclear','fisica-moderna--fissao-nuclear','Observe uma representação esquemática de uma reação em cadeia de fissão.','Ensino médio',true),
  ('Relatividade e espaço-tempo','Física moderna e nuclear','fisica-moderna--relatividade','Explore uma representação didática de referenciais e dilatação do tempo; o desenho é uma analogia visual.','Ensino médio',true)
on conflict (slug) do nothing;

insert into public.animations(title,topic,slug,summary,level,is_published)
values ('Processo de Penrose','Física moderna','fisica-moderna--processo-penrose','Modelo didático do processo de Penrose e da extração de energia rotacional de um buraco negro.','Ensino médio',false)
on conflict (slug) do nothing;
commit;
